reindex:
  cron: "0 9 * * 0"
  class: Solr::ReindexJob
  queue: default
notify:
  cron: "30 8 * * *"
  class: SubscriptionJob
  queue: default
sitemap_generation:
  cron: "15 12 * * *"
  class: SitemapJob
  queue: default
