reindex:
  cron: "0 9 * * 0"
  class: ReindexJob
  queue: default
notify:
  cron: "30 8 * * *"
  class: SubscriptionJob
  queue: mailers
sitemap_generation:
  cron: "15 12 * * *"
  class: SitemapJob
  queue: default
cleanup_unconfirmed:
  cron: "0 4 * * *"
  class: CleanupJob
  queue: default
