amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws[:access] %>
  secret_access_key: <%= Rails.application.credentials.aws[:secret] %>
  region: <%= Rails.application.credentials.aws[:region] %>
  bucket: <%= Rails.application.credentials.aws[:bucket] %>-<%= Rails.env %>
test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>
