test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/test

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/development

# staging:
#   solr:
#     hostname: localhost
#     port: 8983
#     log_level: WARNING
#     path: /solr/production
#     # read_timeout: 2
#     # open_timeout: 0.5
# 
# production:
#   solr:
#     hostname: localhost
#     port: 8983
#     log_level: WARNING
#     path: /solr/production
#     # read_timeout: 2
#     # open_timeout: 0.5
